eureka:
  client:
    service-url:
      default-zone: http://micro.local:8761/eureka/
    healthcheck:
      enabled: true

feign:
  hystrix:
    enabled: true

server:
  port: 8765
spring:
  application:
    name: service-feign
