server:
  port: 8777
  servlet:
    context-path: /api

spring:
  profiles:
    active: @profileActive@
  datasource:
    druid:
      url: jdbc:mysql://192.168.168.65:3306/scaffold?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: mysql
      password: mysql
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


# ====================MybatisPlus Config====================
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath*:/mapper/*Mapper.xml
  mapper-locations: classpath:/com/jasper/scaffold/**/mapper/xml/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.jasper.scaffold.*.entity
  # 支持统配符 * 或者 ; 分割
  type-enums-package: com.jasper.scaffold.api.entity.enums
  global-config:
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    db-config:
      #mp2.3+ 全局表前缀 mp_
      #table-prefix: mp_
      #刷新mapper 调试神器
      #refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
      # 逻辑删除配置
      logic-delete-field: mark # 全局逻辑删除字段 实体类上有 @TableLogic 则以实体上的为准，忽略全局
      logic-delete-value: 1
      logic-not-delete-value: 0

    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
#===================================================================================